swagger: '2.0'
info:
  version: '1.0'
  title: "Valsugana Bees API"
  description: >-
    This is an API specification for the Software Engineering 2 group project (University of Trento).
    The API is developed by ValsuganaBees.
  license:
    name: MIT
    url: https://github.com/xates/se2-project/blob/master/LICENSE
host: se2-project.herokuapp.com
basePath: /v1
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /users:
    x-summary: Users Collection
definitions:
  User:
    type: "object"
    description: "Object representing a user"
    required:
      - "email"
      - "username"
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
        description: "ID of the user"
      email:
        type: string
        format: email
        description: "Email address of the user"
      username:
        type: string
        description: "Username of the user"
      firstName:
        type: string
        description: "First name of the user"
      lastName:
        type: string
        description: "Last name of the user"
      registrationTime:
        type: integer
        format: timestamp
        readOnly: true
        description: "Registration time of the user"
  Group:
    type: "object"
    description: "Object representing a group of users"
    required:
      - "name"
      - "users"
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
        description: "ID of the group"
      name:
        type: string
        description: "Name of the group"
      description:
        type: string
        description: "Description of the group"
      users:
        type: array
        items:
          type: integer
          format: int64
        uniqueItems: true
        description: "Users belonging to the group"
      creator:
        type: integer
        format: int64
        readOnly: true
        description: "User that created the group"
      public:
        type: boolean
        description: "Indicates if the group is public"
      creationTime:
        type: integer
        format: timestamp
        readOnly: true
        description: "Creation time of the group"
  Task:
    type: "object"
    description: "Object representing a task (an assignment)"
    required:
      - "title"
      - "assignment"
      - "type"
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
        description: "ID of the task"
      title:
        type: string
        description: "Title of the task"
      assignment:
        type: string
        description: "Assignment of the task"
      type:
        type: string
        description: "Type of the task"
      creator:
        type: integer
        format: int64
        readOnly: true
        description: "User that created the task"
      creationTime:
        type: integer
        format: timestamp
        readOnly: true
        description: "Creation time of the task"
  Pool:
    type: "object"
    description: "Object representing a pool of tasks"
    required:
      - "name"
      - "tasks"
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
        description: "ID of the pool"
      name:
        type: string
        description: "Name of the pool"
      description:
        type: string
        description: "Description of the pool"
      tasks:
        type: array
        items:
          type: integer
          format: int64
        uniqueItems: true
        description: "Tasks composing the pool"
      creator:
        type: integer
        format: int64
        readOnly: true
        description: "User that created the pool"
      public:
        type: boolean
        description: "Indicates if the pool is public"
      creationTime:
        type: integer
        format: timestamp
        readOnly: true
        description: "Creation time of the pool"
  Exam:
    type: "object"
    description: "Object representing an exam (test)"
    required:
      - "name"
      - "pool"
      - "group"
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
        description: "ID of the exam"
      name:
        type: string
        description: "Name of the exam"
      description:
        type: string
        description: "Description of the exam"
      pool:
        type: integer
        format: int64
        description: "Pool of tasks used for the exam"
      group:
        type: integer
        format: int64
        description: "Group of people doing the exam"
      tasksPerPaper:
        type: integer
        description: "Number of tasks assigned to each paper (to each user)"
      startTime:
        type: integer
        format: timestamp
        description: "Start time of the exam"
      deadline:
        type: integer
        format: timestamp
        description: "Deadline of the exam"
      creator:
        type: integer
        format: int64
        readOnly: true
        description: "User that created the exam"
      creationTime:
        type: integer
        format: timestamp
        readOnly: true
        description: "Creation time of the exam"
  Paper:
    type: "object"
    description: "Object representing a paper (an instance of an exam assigned to a specific user)"
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
        description: "ID of the paper"
      exam:
        type: integer
        format: int64
        readOnly: true
        description: "Exam relative to the paper"
      user:
        type: integer
        format: int64
        readOnly: true
        description: "User assignee of the paper"
      tasks:
        type: array
        items:
          type: integer
          format: int64
        uniqueItems: true
        readOnly: true
        description: "Tasks composing the paper"
      mark:
        type: number
        description: "Mark of the paper"
  Submission:
    type: "object"
    description: "Object representing a submission (an answer to a task)"
    required:
      - "exam"
      - "task"
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
        description: "ID of the submission"
      user:
        type: integer
        format: int64
        readOnly: true
        description: "User that submitted the submission"
      exam:
        type: integer
        format: int64
        description: "Exam relative to the submission"
      task:
        type: integer
        format: int64
        description: "Task relative to the submission"
      creationTime:
        type: integer
        format: timestamp
        readOnly: true
        description: "Creation time of the submission"
  Review:
    type: "object"
    description: "Object representing a review (relative to a submission)"
    required:
      - "mark"
      - "comment"
      - "submission"
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
        description: "ID of the review"
      user:
        type: integer
        format: int64
        readOnly: true
        description: "User that submitted the review"
      submission:
        type: integer
        format: int64
        description: "Submission relative to the review"
      mark:
        type: number
        description: "Mark of the review"
      comment:
        type: string
        description: "Comment of the review"
      creationTime:
        type: integer
        format: timestamp
        readOnly: true
        description: "Creation time of the review"
