swagger: '2.0'
info:
  version: '1.0'
  title: "ValsuganaBees API"
  description: >-
    This is an API specification for the Software Engineering 2 group project (University of Trento). 
    The API is developed by ValsuganaBees.
  license:
    name: MIT
host: se2-project.herokuapp.com
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /users:
    x-summary: Users Collection
  /teachers:
    x-summary: Teachers Collection
  /students:
    x-summary: Students Collection.
  /tasks:
    x-summary: Tasks Collection
  /exams:
    x-summary: Exams Collection
