swagger: '2.0'
info:
  version: '1.0'
  title: "ValsuganaBees API"
  description: >-
    This is an API specification for the Software Engineering 2 group project (University of Trento). 
    The API is developed by ValsuganaBees.
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: se2-project.herokuapp.com
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /users:
    x-summary: Users Collection
    get:
      summary: List All Users
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/RegisteredUser'
          examples:
            application/json:
              name: "Marco Rossi"
              username: "marchetto"
              email: "marco@mail.prova"
    post:
      description: >-
        You can register a user using this action. It takes a JSON
        object containing a name, username and email.
      summary: Register new User
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/NewUser'
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/RegisteredUser'
          examples:
            application/json:
              id: "New id"
              name: "New User"
              username: "newuser"
              email: "new@user.test"
definitions:
  NewUser:
    title: New User
    type: object
    properties:
      name:
        type: string
      username:
        type: string
      email:
        type: string
    required:
      - name
      - username
      - email
  RegisteredUser:
    title: Registered User
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      username:
        type: string
      email:
        type: string
    required:
      - id
      - name
      - username
      - email
